### ISSUE TITLE
Ошибка при тестировании пакета 1testrunner

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/1testrunner#5]
При сборке пакетов получена ошибка в тестах

![image](https://cloud.githubusercontent.com/assets/2657561/18355542/1316d600-75f2-11e6-82d2-385855a0a3fe.png)

Призываю @artbear

**Comment by artbear** [comment]
Посмотрю

**Comment by artbear** [comment]
@EvilBeaver В какой ветке ошибка?

**Comment by artbear** [comment]
Похоже, что у тебя logos какой-то старый :(
Ручные тесты библиотеки и 1testrunner прошли нормально.
почему у тебя вообще при запуске тестов asserts показываются ошибки других тестов?

**Comment by artbear** [comment]
В Jenkins также полный цикл CI библиотеки и 1testrunner успешно прошел.

Зачем у тебя в команде юзается `xddReportPath .` ? 
Может быть, с этим какая-то проблема?

**Comment by EvilBeaver** [comment]
Проблема с раннером, но logos, действительно может быть старый. А от каких нововведений logos-a зависит тестраннер?

**Comment by artbear** [comment]
Последние правки логоса - Лог.Отладка и прочее работают как СтрШаблон

**Comment by EvilBeaver** [comment]
Да, значит это у меня старый логос. Надо перенастроить CI, чтобы при тестировании использовал библиотеки, которые лежат тут же, а не те, что установлены на серваке в качестве основных.
